prometheus:
  prometheusSpec:
    remoteWrite:
    - url: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-xxx/api/v1/remote_write"
      # Replace with your AMP workspace URL
    
    additionalScrapeConfigs:
    - job_name: 'myapp'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

grafana:
  adminPassword: "prom-operator"
  service:
    type: LoadBalancer
  # Pre-configured dashboards for EKS metrics
